image:
  repository: ghcr.io/onedr0p/plex
env:
  TZ: Europe/Oslo
service:
  main:
    type: LoadBalancer
    ports:
      http:
        port: 32400
      dlna-udp:
        port: 1900
        protocol: UDP
      bonjour:
        port: 5353
        protocol: UDP
      companion:
        port: 8324
        protocol: TCP
      gdm-1:
        port: 32410
        protocol: UDP
      gdm-2: 
        port: 32412
        protocol: UDP
      gdm-3: 
        port: 32413
        protocol: UDP
      gdm-4: 
        port: 32414
        protocol: UDP
      dlna-tcp:
        port: 32469
        protocol: TCP
controller:
  type: statefulset
ingress:
  main:
    enabled: true
    ingressClassName: kong
    hosts:
      - host: "plex.taldev.no"
        paths:
          - path: /
            service:
              name: plex
              port: 32400
persistence:
  config:
    enabled: true
  movies:
    enabled: true
    existingClaim: plex-movies-nfs
  tv:
    enabled: true
    existingClaim: plex-tv-nfs
storage:
  tv:
    server: nas.g69.io
    path: /mnt/user/Video/Serier
  movies:
    server: nas.g69.io
    path: /mnt/user/Video/Filmer
