image:
  repository: ghcr.io/onedr0p/plex
env:
  TZ: Europe/Oslo
service:
  type: LoadBalancer
  main:
    ports:
      http:
        port: 32400
controller:
  type: statefulset
ingress:
  main:
    enabled: true
    ingressClassName: kong
    hosts:
      - host: "plex.taldev.no"
        paths:
          - path: /
            service:
              name: plex
              port: 32400
persistence:
  config:
    enabled: true
  movies:
    enabled: true
    existingClaim: plex-movies-nfs
  tv:
    enabled: true
    existingClaim: plex-tv-nfs
storage:
  tv:
    server: nas.g69.io
    path: /mnt/user/Video/Serier
  movies:
    server: nas.g69.io
    path: /mnt/user/Video/Filmer
