vault:
  standalone:
    enabled: true
  server:
    ingress:
      enabled: true
      ingressClassName: "kong"
      pathType: Prefix
      activeService: true
      hosts:
        - host: vault.taldev.no
          paths: 
          - path: /*
            backend:
              service: vault-prod
              port:
                number: 8200
