{% comment %} apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace:
spec:
  rules:
  - host: radarr.taldev.no
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 7878
  ingressClassName: kong {% endcomment %}