apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-iscsi
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 10.0.69.10:3260
    iqn: iqn.2022-11.io.g69:radarr
    lun: 0
    fsType: 'ext4'
    initiatorName: iqn.2022-11.io.g69:radarr-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-media-nfs
  namespace: media
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.69.10
    path: "/mnt/user/Video/Filmer"
  mountOptions:
    - nfsvers=3