apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-iscsi
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 10.0.69.10:3260
    iqn: iqn.2022-11.io.g69:radarr
    lun: 0
    fsType: 'ext4'