apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-tv-nfs
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: {{ .Values.storage.tv.server }}
    path: {{ .Values.storage.tv.path }}
  mountOptions:
    - nfsvers=3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-movies-nfs
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: {{ .Values.storage.movies.server }}
    path: {{ .Values.storage.movies.path }}
  mountOptions:
    - nfsvers=3