apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name}}-config-iscsi
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: {{ .Values.storage.config.targetPortal }}
    iqn: {{ .Values.storage.config.iqn }}
    lun: {{ .Values.storage.config.lun }}
    fsType: {{ .Values.storage.config.fsType | quote }}
    initiatorName: {{ .Values.storage.config.initiatorName }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-media-nfs
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: {{ .Values.storage.media.server }}
    path: {{ .Values.storage.media.path }}
  mountOptions:
    - nfsvers=3