apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-iscsi
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 10.0.69.10:3260
    iqn: iqn.2018-11.no.taldev.unraid:sonarr-config
    lun: 0
    fsType: "ext4"
    initiatorName: iqn.2018-11.no.taldev.k8s:sonarr-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-media-nfs
  namespace: media
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.69.10
    path: /mnt/user/Video/Serier
  mountOptions:
    - nfsvers=3