apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-media-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: sonarr-media-nfs