sonarr:
  TZ: Europe/Oslo
  ingress:
    main:
      enabled: true
      ingressClassName: kong
      hosts:
        - host: "sonarr.taldev.no"
          paths:
            - path: /
              service:
                name: sonarr
                port: 8989
  persistence:
    config:
      volumeName: sonarr-config-iscsi
      size: 2Gi
    media:
      size: 1Mi
      volumeName: sonarr-media-nfs
      mountPath: /media