sonarr:
  TZ: Europe/Oslo
  ingress:
    main:
      enabled: true
      ingressClassName: kong
      hosts:
        - host: "sonarr.taldev.no"
  persistence:
    config:
      volumeName: sonarr-config-iscsi
    media:
      volumeName: sonarr-media-nfs