env:
  TZ: Europe/Oslo
persistence:
  config:
    enabled: true
    type: pvc
    existingClaim: radarr-config-iscsi
  media:
    enabled: false
    #type: pvc
    #existingClaim: radarr-nfs-video
ingress:
  main:
    enabled: true
    ingressClassName: "kong"
    hosts:
      - host: "radarr.taldev.no"
        paths:
          - path: /
            service: 
              name: radarr
              port: 
                number: 7878
          